import React from "react";
import Head from "next/head";
import groq from "groq";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import { FooterHero, Search, Categories, PremiumAds } from "../components";
import { client } from "../lib/client";

export default function Home({ locale, pins }) {
  return (
    <div className="">
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {console.log("This is a Pin", pins)}
      <Search />
      <h2 className="text-3xl text-red-500">{locale}</h2>
      <Categories />
      <PremiumAds pins={pins} />
      <FooterHero />
    </div>
  );
}

export const getStaticProps = async ({ locale }) => {
  const query = groq`
    *[_type == 'comment']
  `;
  const pins = await client.fetch(query);

  return {
    props: {
      pins,
      ...(await serverSideTranslations(locale, ["home"])),
    },
  };
};
